### PR TITLE
New Committee Photos

### PR DESCRIPTION
**Pull request by Emersont1**

### CODE REVIEW

**Comment by Emersont1** [comment]
@AlexanderOrgill and Liam, if you upload your photo's here, we can whack it on the new site

**Comment by L-E2021** [comment]
Liam here, took me a while to figure this out sorry, been super busy. Attached should be my beautiful face. 
Snapchat-1554646475

**Comment by zac-garby** [comment]
i've added myself as graphics officer, but that makes my face appear twice. not sure what the best way to format this would be

**Comment by dthelegend** [comment]
Picture for me (Daudi Wampamba Bandres)
image

**Comment by Emersont1** [comment]
@zac-garby has Daudi been added to the PR

also waiting on 
@abimabi 
@alisha-dadar 
@AlexanderOrgill

**Comment by zac-garby** [comment]
not yet, will sort later

**Comment by UnicornsOnLSD** [comment]
Closing to make yet another PR for new committee photos

**Pull request closed without merging**
