### PR TITLE
Added capability for custom event colours in calendar

### PR DESCRIPTION
**Pull request by wander-igdst**
Hello!
Added different colors for Workshops / MLH / HacktoberFest / Intro Sessions / Others. Default will be Green in colour.

Screen Shot 2019-10-19 at 2 31 29 PM

This is for issue : https://github.com/HackSocNotts/hacksocnotts.co.uk/issues/95 
Thanks!

### CODE REVIEW

**Review by DanielCordell — CHANGES_REQUESTED** [review]
The overall change is perfect and works how we would like, however, it seems like your linter was on when you made the changes. We can't accept this change until the formatting has been changed back, so it's consistent with the rest of the codebase. CalendarPage.jsx, EventPage.jsx and eventsInitialState.jsx are the files in question.

**Comment by wander-igdst** [comment]
@DanielCordell Thanks for taking time to review. I have made changes to comply with the formatting standards of the repository. Kindly let me know if we need to make any more changes.

**Comment by DanielCordell** [comment]
@wander-igdst Hey sorry! been a busy week, will get to it!

**Comment by wander-igdst** [comment]
@DanielCordell Hey sure thanks!

**Pull request closed without merging**
