### PR TITLE
Save event times as local time

### LINKED ISSUE #90: ICS file doesn't respect London Time Zone
Our ICS file generation in [/scripts/generateICS.js](https://github.com/HackSocNotts/hacksocnotts.co.uk/blob/master/scripts/generateICS.js) just sets all events to UTC. When generating the file it should generate it using GMT and BST where applicable as all events are run in the UK Local Time.

### PR DESCRIPTION
**Pull request by arvidboivie**
fixes #90. 

This solves the issues by saving the times as local time. Perhaps you wanted a different solution of saving them as UTC but with the correct offset?

### CODE REVIEW

**Review by erinosher — CHANGES_REQUESTED** [review]
I don't believe the fields you've added are valid as it's resulted in the file just containing "null".

You are right in assuming that I'm partial to the plugin calculating the offset though.

You can check what's been generated here: https://hacksocnotts-pr-101.herokuapp.com/calendar.ics

**Comment by arvidboivie** [comment]
Hmm, that’s strange. I tried it locally and got the generated ics file without the ‘Z’ notation.

**Comment by arvidboivie** [comment]
My bad, the ics package needed an upgrade and I lost that in my first commit. Should work now.

**Review by erinosher — APPROVED** [review]
I've had to update your lock files to get it to build. But I'm happy with this change for now.

**Pull request merged**
