### PR TITLE
[support] CircleCI config refactor to ... 

### PR DESCRIPTION
**Pull request by jacekk**
... use workflow and filter deploy job by branch using build-in feature. Should not change much though :/

### CODE REVIEW

**Comment by jacekk** [comment]
@aaronosher executors are supported since `version: 2.1` --> https://circleci.com/docs/2.0/configuration-reference/#executors-requires-version-21

EDIT:
Top level `version` set to 2.1 should work. No need to add `version` into workflows.

**Review by erinosher — CHANGES_REQUESTED** [review]
Hi @jacekk 👋 

Thanks for contributing and happy hacktoberfest 🎃 

I noticed a few errors initially with the config and corrected them I hope you're alright with that.

It appears that one of the features you used, `executors` isn't supported in the v2 CircleCI API. I'm aware that it can be enabled by toggling the v2.1 API. However, given that our configuration is already fit for purpose, I'm inclined to leave it as is.

If you want to make it v2 compatible, I can discuss with our @HackSocNotts/dev-secretary team and decide whether or not to merge it from there. But do note, there are also other factors pertaining to our internal operations that may prevent us from going ahead with a configuration change.

**Comment by jacekk** [comment]
@aaronosher Totally understandable. Just wanted to play&learn CircleCI on a diffrent project; different than my day-job project ;) Apparently, still a lot I can learn :/

**Comment by erinosher** [comment]
> @aaronosher Totally understandable. Just wanted to play&learn CircleCI on a diffrent project; different than my day-job project ;) Apparently, still a lot I can learn :/

That's fair. I'd recommend messing around with it on projects using your own account, and not on other people's. 

I'm gonna go ahead and close this PR.

Happy hacking 🎃

**Pull request closed without merging**
