### PR TITLE
Committee photos

### PR DESCRIPTION
**Pull request by taradilley**

### CODE REVIEW

**Comment by DanielCordell** [comment]
Gun somewhat jumped but I'll leave it here and use it as the PR.

**Review by erinosher — CHANGES_REQUESTED** [review]
Mia is still missing

**Comment by DanielCordell** [comment]
Yes I cannot count good job

**Review by erinosher — DISMISSED** [review]
As far as I can tell, I'm happy now. @DanielCordell can you go through everything before merging, please.

**Comment by erinosher** [comment]
@DanielCordell I added the @HackSocNotts/hacknotts-organisers to it. Review pls

**Review by DanielCordell — APPROVED** [review]

**Pull request merged**
